### ISSUE TITLE
Cant't transfere to/from Edge and Chrome

### ISSUE THREAD

**Issue by johmor52** [Offerel/SyncMarks-Extension#45] opened 2021-03-19 13:56 UTC
**Describe the bug**
Can connect to webapp. (without open tab in local net.
When import, nothing happens if not choose delete.
When choose delete Yes - local bookmarks deletes, but still no download.

Log chrome extension:
2021-03-19 13:49:39 - 5997 changes on the server since the last sync.
Import not deleting - no action

Import and deleting:
2021-03-19 13:50:55 - Info: Try to remove all local bookmarks
2021-03-19 13:50:55 - Info: Sending import request to server
2021-03-19 13:50:55 - Info: Starting bookmark import from server
- No bookmarks arrived

Did a new test local net:
Hera are setting and logs.
[chromes-settings.txt](https://github.com/Offerel/SyncMarks-Extension/files/6171545/chromes-settings.txt)
[SyncMarks-extension-chrome.log](https://github.com/Offerel/SyncMarks-Extension/files/6171547/SyncMarks-extension-chrome.log)
[syncmarks-webapp.log](https://github.com/Offerel/SyncMarks-Extension/files/6171548/syncmarks-webapp.log)

**Comment by Offerel** [comment] 2021-03-19 16:13
> **Describe the bug**
> Can connect to webapp. (without open tab in local net.
> When import, nothing happens if not choose delete.
> When choose delete Yes - local bookmarks deletes, but still no download.

Thats the expected behavior.

> Log chrome extension:
> 2021-03-19 13:49:39 - 5997 changes on the server since the last sync.
> Import not deleting - no action
>

Where do you get this logline? This looks like to be from startup sync, but not from Import action.

> Import and deleting:
> 2021-03-19 13:50:55 - Info: Try to remove all local bookmarks
> 2021-03-19 13:50:55 - Info: Sending import request to server
> 2021-03-19 13:50:55 - Info: Starting bookmark import from server
>
>     * No bookmarks arrived

Is there some error message? There should be one, if no bookmarks can be imported. I need this to analyse, whats going on. Please look also at the server. Maybe there is a JSON error, when the bookmarks are corrupted.

>
> Did a new test local net:
> Hera are setting and logs.
> [chromes-settings.txt](https://github.com/Offerel/SyncMarks-Extension/files/6171545/chromes-settings.txt)
> [SyncMarks-extension-chrome.log](https://github.com/Offerel/SyncMarks-Extension/files/6171547/SyncMarks-extension-chrome.log)
> [syncmarks-webapp.log](https://github.com/Offerel/SyncMarks-Extension/files/6171548/syncmarks-webapp.log)

```
[19-Mar-2021 14:46:38] - [notice] - johan@hemkonto.se - 192.168.9.10 - Request clientname
[19-Mar-2021 14:46:38] - [debug] - johan@hemkonto.se - 192.168.9.10 - SELECT cname, ctype FROM clients WHERE cid = '4675e5df-e050-4a1b-84d5-e6d30b90a7c0' and uid = 1;
[19-Mar-2021 14:46:38] - [notice] - johan@hemkonto.se - 192.168.9.10 - Send name '4675e5df-e050-4a1b-84d5-e6d30b90a7c0' back to client
[19-Mar-2021 14:46:56] - [debug] - johan@hemkonto.se - 192.168.9.10 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[19-Mar-2021 14:46:56] - [notice] - johan@hemkonto.se - 192.168.9.10 - Browser requested bookmark import...
[19-Mar-2021 14:46:56] - [notice] - johan@hemkonto.se - 192.168.9.10 - Get bookmarks
[19-Mar-2021 14:46:56] - [debug] - johan@hemkonto.se - 192.168.9.10 - SELECT * FROM `bookmarks` WHERE `bmAction` IS NULL AND `userID` = 1;
```

It seems, that creating the JSON response from the bookmarks at the server is not completed at this stage. But this is the last line in your logfile. There must be something later. I expect a line like "587 bookmarks send to client.". You can also try to set `$cexpjson = true;` in _config.inc.php_. This will save the bookmarks as JSON file (_export_clientid_time.json_) at the server. You can inspect that with a JSON validator, if the file is valid.

**Comment by johmor52** [comment] 2021-03-21 09:58
Still no import from Chrome (exported from Firefox).
[Chrom-extension webapp.txt](https://github.com/Offerel/SyncMarks-Extension/files/6177167/Chrom-extension.webapp.txt)

**Comment by Offerel** [comment] 2021-03-21 13:13
`DB update failed: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: clients.cid`
You have an issue with the clientid 2ce69aff-7ad9-4332-b645-5d9a32c6e904. This client is already connected to another user.

```
[20-Mar-2021 20:37:28] - [notice] - johan@hemkonto.se - 31.208.210.52 - Requested bookmark export...
[20-Mar-2021 20:37:28] - [notice] - johan@hemkonto.se - 31.208.210.52 - Exporting in JSON format
[20-Mar-2021 20:37:28] - [notice] - johan@hemkonto.se - 31.208.210.52 - Get bookmarks
[20-Mar-2021 20:37:28] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `bookmarks` WHERE `bmAction` IS NULL AND `userID` = 2;
[20-Mar-2021 20:40:06] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[20-Mar-2021 20:40:06] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[20-Mar-2021 20:40:06] - [notice] - johan@hemkonto.se - 31.208.210.52 - Try to show logfile
```
At the next step, your export is not finished, that's why it isn't send to the client. At this stage. I expected a line with something like `1200 bookmarks send to the client`. You should wait some time longer. If the export fails/transfer fails, there will be an error message.  Ad said before, you can try to inspect the JSON message, with the bookmarks, which will be send to the browser. You should set `$cexpjson = true;` in config.inc.php for this. If the JSON is valid and the bookmarks are valid bookmarks, the import should work.

**Comment by johmor52** [comment] 2021-03-21 21:05
One problem is Client name:
If I set a new, it will disappear when next restart webreader. Why?

Test import to Chrome extension 1.17.11 
I have redused bookmarks til about 200 bookmarks in webapp.
I have three bookmarks in Chrome.

$cexpjson = true

An instance of Chrome logged in.
Open a new Chrome-window
Nothing transfered
The extension log:
2021-03-21 17:57:11 - Info: AddOn version: 1.17.11
2021-03-21 17:57:11 - Info: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
2021-03-21 17:57:11 - Info: Current architecture: x86-64 | Current OS: win
2021-03-21 17:57:11 - Info: Initiate PHP startup sync
2021-03-21 17:57:11 - Info: Get list of clients.
2021-03-21 17:57:11 - Info: Get notifications for current client.
2021-03-21 17:57:11 - Info: Initiate startup sync
2021-03-21 17:57:11 - Info: This browser seems to be a new client for the server. The client is now registered at the server. No bookmarks are imported. You can import them manually.
2021-03-21 17:57:12 - Info: List of 2 clients retrieved successful.

Import - no delete
- no more in extension log.

- Log webapp:
[21-Mar-2021 18:05:30] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[21-Mar-2021 18:05:30] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[21-Mar-2021 18:05:30] - [notice] - johan@hemkonto.se - 31.208.210.52 - Request clientname
[21-Mar-2021 18:05:30] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT cname, ctype FROM clients WHERE cid = '2ce69aff-7ad9-4332-b645-5d9a32c6e904' and uid = 2;
[21-Mar-2021 18:05:30] - [notice] - johan@hemkonto.se - 31.208.210.52 - Undefined offset: 0 in /storage/content/51/140851/hemkonto.se/public_html/SyncMarks/index.php on line 312
[21-Mar-2021 18:05:30] - [notice] - johan@hemkonto.se - 31.208.210.52 - Trying to access array offset on value of type null in /storage/content/51/140851/hemkonto.se/public_html/SyncMarks/index.php on line 313
[21-Mar-2021 18:05:30] - [notice] - johan@hemkonto.se - 31.208.210.52 - Send name '' back to client
[21-Mar-2021 18:05:42] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[21-Mar-2021 18:05:42] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[21-Mar-2021 18:05:42] - [notice] - johan@hemkonto.se - 31.208.210.52 - Try to show logfile

No transfer of bookmarks

Import - yes delete
- The three bookmarks in Chrome was deleted.
Extension log:
2021-03-21 18:08:55 - Info: Try to remove all local bookmarks
2021-03-21 18:08:55 - Info: Sending import request to server
2021-03-21 18:08:55 - Info: Starting bookmark import from server
- Waiting for 3 minutes.......(250Mbit internet)

No more bookmarks in Chrome
Log at webapp:
[21-Mar-2021 18:08:56] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[21-Mar-2021 18:08:56] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[21-Mar-2021 18:08:56] - [notice] - johan@hemkonto.se - 31.208.210.52 - Requested bookmark export...
[21-Mar-2021 18:08:56] - [notice] - johan@hemkonto.se - 31.208.210.52 - Exporting in JSON format
[21-Mar-2021 18:08:56] - [notice] - johan@hemkonto.se - 31.208.210.52 - Get bookmarks
[21-Mar-2021 18:08:56] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `bookmarks` WHERE `bmAction` IS NULL AND `userID` = 2;
[21-Mar-2021 18:08:56] - [notice] - johan@hemkonto.se - 31.208.210.52 - Send now 407 bookmarks to the client
[21-Mar-2021 18:08:56] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `clients` WHERE `cid` = '2ce69aff-7ad9-4332-b645-5d9a32c6e904' AND uid = 2;
[21-Mar-2021 18:08:56] - [notice] - johan@hemkonto.se - 31.208.210.52 - New client detected. Register client 2ce69aff-7ad9-4332-b645-5d9a32c6e904 for user johan@hemkonto.se
[21-Mar-2021 18:08:56] - [debug] - johan@hemkonto.se - 31.208.210.52 - INSERT INTO `clients` (`cid`,`cname`,`ctype`,`uid`,`lastseen`) VALUES ('2ce69aff-7ad9-4332-b645-5d9a32c6e904','2ce69aff-7ad9-4332-b645-5d9a32c6e904', 'Chrome', 2, '0')
[21-Mar-2021 18:08:56] - [error] - johan@hemkonto.se - 31.208.210.52 - DB update failed: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: clients.cid
[21-Mar-2021 18:14:45] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[21-Mar-2021 18:14:45] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[21-Mar-2021 18:14:45] - [notice] - johan@hemkonto.se - 31.208.210.52 - Try to show logfile





If I choose another of client name I  got in webapp log:
[21-Mar-2021 18:18:34] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[21-Mar-2021 18:18:34] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[21-Mar-2021 18:18:34] - [notice] - johan@hemkonto.se - 31.208.210.52 - Get testrequest from addon options page
[21-Mar-2021 18:18:34] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `clients` WHERE `cid` = '2ce69aff-7ad9-4332-b645-5d9a32c6e904' AND uid = 2;
[21-Mar-2021 18:18:34] - [notice] - johan@hemkonto.se - 31.208.210.52 - New client detected. Register client 2ce69aff-7ad9-4332-b645-5d9a32c6e904 for user johan@hemkonto.se
[21-Mar-2021 18:18:34] - [debug] - johan@hemkonto.se - 31.208.210.52 - INSERT INTO `clients` (`cid`,`cname`,`ctype`,`uid`,`lastseen`) VALUES ('2ce69aff-7ad9-4332-b645-5d9a32c6e904','2ce69aff-7ad9-4332-b645-5d9a32c6e904', 'Chrome', 2, '0')
[21-Mar-2021 18:18:34] - [error] - johan@hemkonto.se - 31.208.210.52 - DB update failed: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: clients.cid
[21-Mar-2021 18:18:34] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[21-Mar-2021 18:18:34] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[21-Mar-2021 18:18:34] - [notice] - johan@hemkonto.se - 31.208.210.52 - Rename client 2ce69aff-7ad9-4332-b645-5d9a32c6e904 to 7f4ca3fe-bef9-4d30-9fa3-7a7d7590bc6f
[21-Mar-2021 18:18:34] - [debug] - johan@hemkonto.se - 31.208.210.52 - UPDATE `clients` SET `cname` = '7f4ca3fe-bef9-4d30-9fa3-7a7d7590bc6f' WHERE `uid` = 2 AND `cid` = '2ce69aff-7ad9-4332-b645-5d9a32c6e904';
[21-Mar-2021 18:18:40] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[21-Mar-2021 18:18:40] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[21-Mar-2021 18:18:40] - [notice] - johan@hemkonto.se - 31.208.210.52 - Try to show logfile

Make another import - Yes delete.
2021-03-21 18:20:26 - Info: Try to remove all local bookmarks
2021-03-21 18:20:26 - Info: Sending import request to server
2021-03-21 18:20:27 - Info: Starting bookmark import from server

Webapp log:
[21-Mar-2021 18:20:27] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[21-Mar-2021 18:20:27] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[21-Mar-2021 18:20:27] - [notice] - johan@hemkonto.se - 31.208.210.52 - Requested bookmark export...
[21-Mar-2021 18:20:27] - [notice] - johan@hemkonto.se - 31.208.210.52 - Exporting in JSON format
[21-Mar-2021 18:20:27] - [notice] - johan@hemkonto.se - 31.208.210.52 - Get bookmarks
[21-Mar-2021 18:20:27] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `bookmarks` WHERE `bmAction` IS NULL AND `userID` = 2;
[21-Mar-2021 18:20:27] - [notice] - johan@hemkonto.se - 31.208.210.52 - Send now 407 bookmarks to the client
[21-Mar-2021 18:20:27] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `clients` WHERE `cid` = '2ce69aff-7ad9-4332-b645-5d9a32c6e904' AND uid = 2;
[21-Mar-2021 18:20:27] - [notice] - johan@hemkonto.se - 31.208.210.52 - New client detected. Register client 2ce69aff-7ad9-4332-b645-5d9a32c6e904 for user johan@hemkonto.se
[21-Mar-2021 18:20:27] - [debug] - johan@hemkonto.se - 31.208.210.52 - INSERT INTO `clients` (`cid`,`cname`,`ctype`,`uid`,`lastseen`) VALUES ('2ce69aff-7ad9-4332-b645-5d9a32c6e904','2ce69aff-7ad9-4332-b645-5d9a32c6e904', 'Chrome', 2, '0')
[21-Mar-2021 18:20:27] - [error] - johan@hemkonto.se - 31.208.210.52 - DB update failed: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: clients.cid
[21-Mar-2021 18:22:33] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[21-Mar-2021 18:22:33] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[21-Mar-2021 18:22:33] - [notice] - johan@hemkonto.se - 31.208.210.52 - Try to show logfile

If I test the same with Firefox it works!

It seems to me that the client name is a problem.
The Exstension does not save the name. It in grey and if I set a name it's gone next time I open reader.
DB update failed: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: clients.cid

I would prefer to set a logical name I can remeber and the extension rember.

**Comment by Offerel** [comment] 2021-03-21 21:55
`[21-Mar-2021 18:05:30] - [notice] - johan@hemkonto.se - 31.208.210.52 - Undefined offset: 0 in /storage/content/51/140851/hemkonto.se/public_html/SyncMarks/index.php on line 312`

For some reason, no client name is set. Either the client has no name specified, or it was removed for some other reason. can you please check, if the client 2ce69aff-7ad9-4332-b645-5d9a32c6e904 exist for the user in the database? You can query with `SELECT cname, ctype FROM clients WHERE cid = '2ce69aff-7ad9-4332-b645-5d9a32c6e904' and uid = 2;`

`[21-Mar-2021 18:08:56] - [notice] - johan@hemkonto.se - 31.208.210.52 - Send now 407 bookmarks to the client`

Here the export is finished successful and 407 entries are send to the client. This are bookmarks and folders. Since you have set saving the json file at the server, you should have there a json file with all the bookmarks. What I not understand, is the next line:

`[21-Mar-2021 18:08:56] - [debug] - johan@hemkonto.se - 31.208.210.52 - SELECT * FROM clients WHERE cid = '2ce69aff-7ad9-4332-b645-5d9a32c6e904' AND uid = 2;
[21-Mar-2021 18:08:56] - [notice] - johan@hemkonto.se - 31.208.210.52 - New client detected. Register client 2ce69aff-7ad9-4332-b645-5d9a32c6e904 for user johan@hemkonto.se
`
Here it try to register the client 2ce69aff-7ad9-4332-b645-5d9a32c6e904 again, since it didn't exist for this user. It seems that this client does not exist or at least not for this user or the client could not registered for this user, because the same clientid exist for another user. You can't register a client more than one time. Or the database is write protected...

A little bit later you get the error:
`[21-Mar-2021 18:18:34] - [error] - johan@hemkonto.se - 31.208.210.52 - DB update failed: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: clients.cid`
The clientid seems to exist already in your database, i assume for a other username. But the clientid has to be unique across the db. You can't have the same clientid more than one time. It doesn't matter if this a other user.

You can set a logical name for sure, but the clientid must be unique. If it exists already the client will not be saved, and if it's not saved it can't send you the logical name back.

**Comment by johmor52** [comment] 2021-03-22 21:51
Now I have tested in my network. Then the login works alright.
Firefox works, but import - No delete don't work.
Chrome no transfer of bookmarks.
I have logged and described all I've done. Hopefully you can follow what happens after every step.
I hope this is useful for you in the process to reduce bugs.

I still have the strange connection problem. I think it must be the router firewall witch don't open for incoming connection when it comes from extension to begin with. I haven't logged that yet.
Or do you have any other explanation?
Here are my files:
[20210321 Linux installation 1.4.2.zip](https://github.com/Offerel/SyncMarks-Extension/files/6185468/20210321.Linux.installation.1.4.2.zip)

**Comment by Offerel** [comment] 2021-03-23 09:02
After checking your logfiles, I found 2 things. According to 11-Chrome Import-yes.log, creating the export is started, however it seems not to be finished, at least, there is now hint, how many bookmarks are exported, the last lines are:
```
[22-Mar-2021 22:18:27] - [notice] - johan@hemkonto.se - 192.168.9.10 - Requested bookmark export...
[22-Mar-2021 22:18:27] - [notice] - johan@hemkonto.se - 192.168.9.10 - Exporting in JSON format
[22-Mar-2021 22:18:27] - [notice] - johan@hemkonto.se - 192.168.9.10 - Get bookmarks
[22-Mar-2021 22:18:27] - [debug] - johan@hemkonto.se - 192.168.9.10 - SELECT * FROM `bookmarks` WHERE `bmAction` IS NULL AND `userID` = 2;
```
After that, there is nothing. Either the select `SELECT * FROM `bookmarks` WHERE `bmAction` IS NULL AND `userID` = 2` fails, in this case, you would see this in the logfile, or it will succeed. In this case, you will get in the logfile a message, that x bookmarks are send to the server. As of this, nothing is send back to the browser. That's why, you didn't see anything in Chrome, but the local bookmarks are deleted. I have currently 1700 bookmarks for a test for my second user. The export was completed after 1 second and written to the export file ($cexpjson = true). After this, it was transferred to the client and imported there. The server is an old Raspberry PI 1, Webserver is nginx with PHP 7.3. Importing took 3 seconds in ungoogled Chromium. I have no idea, why your export will not be finished. 

Please set temporary `$cexpjson = true` and send me the JSON file, maybe i found something in the bookmarks. If that is failing, you can try fire the select by hand and check by yourself. You can use the SQL from the logfile mentioned above.

The next finding is from `3-syncmarks - after 2 login and logout .log`. I dont know if this is related:
```
[22-Mar-2021 21:20:17] - [notice] - johan@hemkonto.se - 192.168.9.10 - Send name 'F-cool' back to client
[22-Mar-2021 21:27:29] - [debug] -  - ::1 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[22-Mar-2021 21:27:29] - [notice] -  - ::1 - Check login
[22-Mar-2021 21:27:51] - [debug] -  - ::1 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[22-Mar-2021 21:27:51] - [notice] -  - ::1 - Check login
[22-Mar-2021 21:27:51] - [debug] -  - ::1 - SELECT * FROM `users` WHERE `userName`= 'admin';
[22-Mar-2021 21:27:51] - [notice] - admin - ::1 - Login successfully
[22-Mar-2021 21:29:32] - [notice] - johan@hemkonto.se - ::1 - Save session to database.
```
You change for some reason your network from ipv4 to ipv6 at `[22-Mar-2021 21:27:29]`. I cant test ipv6 networks from here, because no such network is available here. In theory, this should make no difference, but i cant test this as of now. You change also the user from johan@hemkonto.se to admin and a little bit later back to johan@hemkonto.se, but you stay at the ipv6 network. I couldn't see a real issue here, but maybe this will explain something to you. That's why, its only a "finding" and must not be indicating an issue.

Apart from these two things, I don't see anything unexpected in your log files

**Comment by johmor52** [comment] 2021-03-23 10:40
When I Log in from Debian (localhost) I get ::1 as address in log.
I describe i txt-file how I have tested. Firefox can Import if I select delete-Yes.
Firefox can also delete at webapp when I delete at reader, if there is no duplicate.
Chrome can do nothing of that!

[202123 Import-yes Chrome Firifox.txt](https://github.com/Offerel/SyncMarks-Extension/files/6188795/202123.Import-yes.Chrom.Firifox.txt)

How do I fire the select by hand, how do I send SQL to webapp?

**Comment by Offerel** [comment] 2021-03-23 11:58
Now the logfile looks different:

```
[23-Mar-2021 10:56:10] - [debug] - johan@hemkonto.se - 192.168.9.10 - SELECT * FROM `system` ORDER BY `updated` DESC LIMIT 1;
[23-Mar-2021 10:56:10] - [debug] - johan@hemkonto.se - 192.168.9.10 - SELECT * FROM `users` WHERE `userName`='johan@hemkonto.se'
[23-Mar-2021 10:56:10] - [notice] - johan@hemkonto.se - 192.168.9.10 - Requested bookmark export...
[23-Mar-2021 10:56:10] - [notice] - johan@hemkonto.se - 192.168.9.10 - Exporting in JSON format
[23-Mar-2021 10:56:10] - [notice] - johan@hemkonto.se - 192.168.9.10 - Get bookmarks
[23-Mar-2021 10:56:10] - [debug] - johan@hemkonto.se - 192.168.9.10 - SELECT * FROM `bookmarks` WHERE `bmAction` IS NULL AND `userID` = 2;
[23-Mar-2021 10:56:10] - [notice] - johan@hemkonto.se - 192.168.9.10 - Send now 407 bookmarks to the client
```

In this case, reading the database was successfully and 407 are send to the client. Since you have set `$cexpjson = true`, there should be now the bookmarks as json file in the webapp directory. This is exactly, what is send back to the browser as response. If you want to try it by yourself, you can use for example https://jsonformatter.curiousconcept.com/ or https://jsonlint.com/ for this. Or you can attach the file here. In that case i can check it. I can also try to replicate the same structure here and import it to my Chrome. That's up to you.
```
2021-03-23 10:56:10 - Info: Try to remove all local bookmarks
2021-03-23 10:56:10 - Info: Sending import request to server
2021-03-23 10:56:10 - Info: Starting bookmark import from server
```
The response is received by your chrome client and the import process should start. This should be followed by a line like this: 
`2021-03-23 10:57:11 - Info: 407 bookmarks/folders imported. Re-adding the listeners now`, if the mentioned json file from above is valid and the bookmarks are real bookmarks. If this line is not there, i expect a error either in the log at the client or at least something with a timestamp like this in the browser console.

> When I Log in from Debian (localhost) I get ::1 as address in log.

Maybe something is not properly setup at this machine. Also a request from localhost, should appear at least with the local ip address or 127.0.0.1. For the internal things this doesn't matter, but maybe the http requests can be corrupted in some way. Í haven't such a usecase as of now. If this is working for you, you can ignore it for this specific task, but i would recommend that you check your network configuration. 

> How do I fire the select by hand, how do I send SQL to webapp?

You cant fire an SQL directly to the WebApp, you must do that on database level. You can use every SQLite DB Editor you want for this. I can recommend https://sqlitebrowser.org/ for this. It's lightweight and free. Any other tool will do the same. You can also use your bash shell, if you have the package for sqlite3 installed. For example: `sqlite3 /path/to/your/bookmarks.db`. You will get a new prompt with leading `sqlite>`. Now you enter the SQL request endet by `;`. Hit enter and the SQL will be executed. YOu can leave the shell editor by insert `.q` followed by hit the enter key.

Be aware, that SQLite allows no concurrent write access to a database. If the WebApp does something, access to the file is locked at the same time for other requests until the first request is finished.

**Comment by johmor52** [comment] 2021-03-23 14:24
When I have $cexpjson = true, I got a json file in webapp. I found out that Chrome can't import json, just html or from other reader.
When $cexpjson = false, it also said that transfer was in json format. So it's therefore Chrome can't import the transfer as Firefox can. Is this the correct conclusion? 
How to solve that?
Do have an extension witch makes it possible to import json-files with bookmarks?

**Comment by Offerel** [comment] 2021-03-23 16:02
It doesnt matter if Chrome has this in his menus. The file created at the server is used when importing with the addon, no matter if there is a function in Chrome for this. If the response comes in this format, the addon parses this response and starts the import via the standard bookmark API. This is nearby identical to the one in Firefox. Only the generated id's and default naming schema is different. $cexpjson set to true is only added, to check if the resulting SQL is the expected result for the import. As long as an browser supports WebExtensions and supports the standard bookmark API, it works with this addon. To my knowledge, there is no other addon, what uses this format.

**Comment by johmor52** [comment] 2021-03-23 17:04
My Chrome is 89.0.4389.90 64-bits. I can import from Firefox, but i put a mapp in bookmarksfield with all the bookmarks.
I have no bookmark extension other than SyncMarks.
If your Chrome get updated and can Import bookmarks, why can't mine?
I will test with a other computer and also test with Edge again. Edge acted  as Chrome earlier.
My Edge is 89.0.774.57 64-bit. If I import from Firefox it puts bookmarks more like Firefox have them.
To use SyncMarks I first have function between readers in my net. The connection error is the second to solve.

**Comment by Offerel** [comment] 2021-03-23 20:08
> My Chrome is 89.0.4389.90 64-bits. I can import from Firefox, but i put a mapp in bookmarksfield with all the bookmarks.
I have no bookmark extension other than SyncMarks.

As said before, the term "import" in the AddOn refers to the fact that the response from the webapp will be used in the AddOn  to insert the bookmarks contained in this response. This has nothing to do with any import function of the browser itself. These are completely independent things.

> If your Chrome get updated and can Import bookmarks, why can't mine?
I will test with a other computer and also test with Edge again. Edge acted as Chrome earlier.
My Edge is 89.0.774.57 64-bit. If I import from Firefox it puts bookmarks more like Firefox have them.

I have no idea, whats going on at your side. There can be several reasons. I can try to analyse the issue, if you can show me error message from the client (since the server part looks fine for me). There can be hints in the AddOn log, in the Browser Webconsole or in the JSON response from the server, whats saved as `export_client_timestamp.json` at the server, when you set `$cexpjson = true;`. I can try to import/replicate the bookmarks from within this json file in my dev environment. If this gives me then the same errors, i will have some starting point.

**Comment by johmor52** [comment] 2021-03-25 10:43
I have opened i Router for hemkonto.se. It didn't help for the login problem
Pressing F12 i Chrome and Firefox gave this:
Chrome:
Syncmarks Error: Login failed: Please check username and password.	options.js
xhr.onload @ options.js:58
load (async)
saveOptions @ options.js:50

Firefox:
10:37:45,851 Kaka "PHPSESSID" kommer snart att avvisas eftersom den har "SameSite"-attributet inställt på "None" eller ett ogiltigt värde, utan "secure"-attributet. Läs https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite om du vill veta mer om attributet "SameSite" 									index.php
10:37:45,851 Syncmarks Error: Login failed: Please check username and password. 	options.js:58:15
    onload moz-extension://6fa2db2b-6a99-42c6-9c45-358b3b46048d/scripts/options.js:58

Edge:
Failed to load resource: the server responded with a status of 401 ()	hemkonto.se/SyncMarks/index.php:1 
Uncaught TypeError: Cannot read property 'cname' of undefined		options.js:123
    at XMLHttpRequest.xhr.onload (options.js:123)
POST https://hemkonto.se/SyncMarks/index.php 401			options.js:84
saveOptions @ options.js:84
Syncmarks Error: Login failed: Please check username and password.	options.js:58
xhr.onload @ options.js:58
load (async)
saveOptions @ options.js:50

Could read more at: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
Is it something...

Logging in in another tab made it possible to save options for addon.

Import (insert) from Debian:
When import to Firefox it reloads bookmarks, but Chrome not.

The to *json files i server here: (changed to *txt)
[Chrome-export_2ce69aff_1616666908.txt](https://github.com/Offerel/SyncMarks-Extension/files/6203952/Chrome-export_2ce69aff_1616666908.txt)
[Firefox-export_adf6f19b_1616667344.txt](https://github.com/Offerel/SyncMarks-Extension/files/6203953/Firefox-export_adf6f19b_1616667344.txt)

I have opened in chrome for as much as I can for 192.168.9.14. No change.

**Comment by Offerel** [comment] 2021-03-25 15:09
I have checked both json files. They are valid, I have not imported these files as of now, i will try this in the evening, but for me this file looks fine so far. As for the `samesite ` warning, you can ignore it for now, it is only a deprecation warning. There are ways to work around that. I case for this addon, it doesn't matter, since im not using cookies here. 

The https 401 seems to be, because you send wrong credentials to the backend. I have no idea why this happens. As long, as the saved credentials are correct, something intercepts or at least changes your request somewhere. This can be somewhere in your browser, a third-party application, a proxy, a router, or some other thing. I have tried the addon in several environments, but couldn't find any simple explanation, why correct saved credentials are now transferred as they are saved. 

Looking at line 50 in options.js, I use the value, you have entered in the password field of the options page for credentials to login at the backend and make the testrequest. If this and the username field is filled both with the correct values, you should be able to login. Using empty fields isn't supported.

**Comment by Offerel** [comment] 2021-03-25 21:04
I have tried to import both of your files. It worked as expected in Firefox but surprisingly not in Chromium. The basic format seems to be OK, but for some reason it tries to change the managed folders in Chromium, which isn't possible. This also impossible in Firefox. 

I will try to find a solution at the weekend and will message you back.

**Comment by johmor52** [comment] 2021-03-25 22:11
Great!
I have used Fiddler to inspect what happens at save.
I don't know how to use Fiddler, but I try first time and copied some data.
Maybe it's useful for you.
[Fiddler - Chrome.txt](https://github.com/Offerel/SyncMarks-Extension/files/6208134/Fiddler.-.Chrome.txt)

I changed some login data....
If you know what you want me to log, please tell me.

**Comment by Offerel** [comment] 2021-03-26 08:32
I found the a solution for the Chromium import. It seems that Chromium doesn't have anymore system folder menu________ (Bookmarks Menu). Maybe this didn't exist before. I didn't use Chromium regularly, so i was not aware of this. However,if you now import bookmarks from Firefox to Chrome, it puts bookmarks saved in Firefox "Bookmarks Menu" (Bokmärkesmenyn) folder to "Other Bookmarks" (Andra bokmärken) in Chrome. The names of this folders are language specific. This means, it's not safe, to use the folder menu________ in Firefox in terms of crossbrowser interoperability. I will add this in the next days in the FAQ.

I have made a commit [6051193](https://github.com/Offerel/SyncMarks-Extension/commit/60511932ff2b7fd17563c6a8f61293b89d656e17) with this changes. You can try it, if you want. I will make a full release at the weekend, just want to make sure, that other things works well with this change.

**Comment by johmor52** [comment] 2021-03-26 15:24
Tested in Chrome. Works perfect!
Thank You!

**Closed** 2021-03-26 18:50 UTC
Labels: bug
